{"uuid": "aba728a7-49cb-4971-8b0f-64eb674b100d", "children": ["c02c0099-781c-46cf-9d45-267e127b2209", "7965c28e-62e9-4625-9c6a-b7eb306212d2"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 72, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 257, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754977125016, "stop": 1754977132057}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nNoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:747:5\nassert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:559:13\nassert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4\nGeckoDriver.prototype.maximizeWindow@chrome://remote/content/marionette/driver.sys.mjs:2934:15\ndespatch@chrome://remote/content/marionette/server.sys.mjs:318:40\nexecute@chrome://remote/content/marionette/server.sys.mjs:289:16\nonPacket/<@chrome://remote/content/marionette/server.sys.mjs:262:20\nonPacket@chrome://remote/content/marionette/server.sys.mjs:263:9\n_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:494:20\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 30, in setup\n    driver.maximize_window()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 638, in maximize_window\n    self.execute(command, None)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754977133273, "stop": 1754977151430}], "start": 1754977133273, "stop": 1754977151597}