{"uuid": "b764f284-5482-463e-a951-9a7c1ae83bb1", "children": ["87a60996-ec76-4b1e-bc71-6414113ef75e", "b619ca07-7b4c-47e2-a644-2aa8fbee625a", "6ba932d0-79a5-4b65-8d2c-16fd0302e63a", "b0a4440b-85d8-4ff8-9acc-723a5133e96d"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 72, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 257, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754977125018, "stop": 1754977132163}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 72, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 257, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754977132394, "stop": 1754977149997}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"X:\\Automation Testing\\06. CredKart_Pytest_Revision\\testCases\\conftest.py\", line 29, in setup\n    driver = webdriver.Firefox()\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 58, in __init__\n    if finder.get_browser_path():\n       ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 47, in get_browser_path\n    return self._binary_paths()[\"browser_path\"]\n           ~~~~~~~~~~~~~~~~~~^^\n  File \"X:\\Automation Testing\\03. Pytest Framework\\.venv1\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 78, in _binary_paths\n    raise NoSuchDriverException(msg) from err\n"}, "start": 1754977155072, "stop": 1754977156717}], "start": 1754977155072, "stop": 1754977157073}